"""Add closed_at column in task table

Revision ID: 1cff9ab332f3
Revises: b53656c228e5
Create Date: 2025-12-07 00:10:28.347009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cff9ab332f3'
down_revision: Union[str, Sequence[str], None] = 'b53656c228e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'closed_at')
    # ### end Alembic commands ###
